{% set version = "4.2.1" %}

package:
  name: xraylib-split
  version: {{ version }}

source:
  url: https://github.com/tschoonj/xraylib/releases/download/xraylib-{{ version }}/xraylib-{{ version }}.tar.xz
  sha256: 64f3ffddb327f265c13f05d17b356125a85634d0295be0f0d07bf4b7f9daeb77
  patches:
    # meson's python.extension_module() requires a scalar install_tag;
    # backport of upstream 3b53dae2ad9c382409af146fa9d3037953452fed
    - 0001-Fix-meson-bug.patch

build:
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pkg-config  # [unix]
    - ninja
    - swig
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - meson
    - setuptools
    - numpy
    - cython

outputs:
  - name: libxraylib
    build:
      ignore_run_exports_from:
        - {{ compiler('cxx') }}
      run_exports:
        - {{ pin_subpackage("libxraylib", max_pin="x") }}
    files:
      - lib/libxrl*                       # [unix]
      - lib/pkgconfig/libxrl*.pc          # [unix]
      - include/xraylib/*                 # [unix]
      - Library/bin/xrl*.dll              # [win]
      - Library/lib/xrl*.lib              # [win]
      - Library/lib/pkgconfig/libxrl*.pc  # [win]
      - Library/include/xraylib/*         # [win]
    requirements:
      build:
        - {{ compiler("fortran") }}  # [unix]
        - {{ compiler("c") }}
        - {{ stdlib("c") }}
        - {{ compiler("cxx") }}
      run:
        - ucrt  # [win]
    test:
      requires:
        - {{ compiler('c') }}        # [unix]
        - {{ compiler('cxx') }}      # [unix]
        - {{ compiler('fortran') }}  # [unix]
        - {{ stdlib("c") }}          # [unix]
        - pkg-config                 # [unix]
      files:
        - tests/test.c
        - tests/test.cpp
        - tests/test.f90
        - tests/test.sh
      commands:
        - test -f $PREFIX/include/xraylib/xraylib.h                # [unix]
        - test -f $PREFIX/include/xraylib/xraylib++.h              # [unix]
        - test -f $PREFIX/include/xraylib/xraylib.mod              # [unix]
        - test -f $PREFIX/lib/libxrl${SHLIB_EXT}                   # [unix]
        - test -f $PREFIX/lib/libxrlf03${SHLIB_EXT}                # [unix]
        - test -f $PREFIX/lib/pkgconfig/libxrl.pc                  # [unix]
        - cd tests && bash test.sh                                 # [unix and build_platform == target_platform]
        - if not exist %LIBRARY_LIB%\\pkgconfig\\libxrl.pc exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\xrl.lib exit 1               # [win]
        - if not exist %LIBRARY_INC%\\xraylib\\xraylib.h exit 1    # [win]
        - if not exist %LIBRARY_BIN%\\xrl-11.dll exit 1            # [win]

  - name: xraylib
    build:
      run_exports:
        - {{ pin_subpackage("xraylib", max_pin="x") }}
    files:
      - lib/python*/site-packages/xraylib*    # [unix]
      - lib/python*/site-packages/_xraylib*   # [unix]
      - Lib/site-packages/xraylib*            # [win]
      - Lib/site-packages/_xraylib*           # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - {{ compiler("c") }}
        - {{ stdlib("c") }}
      host:
        - python
        - meson
        - setuptools
        - numpy
        - cython
        - {{ pin_subpackage("libxraylib", exact=True) }}
      run:
        - python
        - {{ pin_subpackage("libxraylib", max_pin="x") }}
    test:
      imports:
        - xraylib
        - xraylib_np

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: license_all.txt
  home: https://github.com/tschoonj/xraylib/wiki
  summary: A library for X-ray matter interaction cross sections for X-ray fluorescence applications

extra:
  feedstock-name: xraylib
  recipe-maintainers:
    - ericdill
    - tacaswell
    - licode
    - tschoonj
    - CJ-Wright
    - mrakitin
